"""Writes immutable audit events for every intercepted tool call."""
import asyncio
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logging import get_logger
from app.models.schemas import AuditEvent

logger = get_logger("audit_writer")

try:
    from app.core.license_gate import get_license_info
    from enterprise.app.services.audit_export.dispatch import AuditEventRecord, dispatch_audit_event
    _export_dispatch_available = True
except ImportError:
    _export_dispatch_available = False


async def write_event(
    session: AsyncSession,
    session_id: uuid.UUID,
    agent_id: uuid.UUID,
    agent_name: str,
    tool_name: str,
    tool_parameters: dict[str, Any],
    decision: str,
    decision_reason: str,
    sequence_number: int,
    duration_ms: int,
    policy_id: Optional[uuid.UUID] = None,
    policy_name: Optional[str] = None,
    tool_response: Optional[dict] = None,
    risk_delta: int = 0,
    input_tokens: Optional[int] = None,
    output_tokens: Optional[int] = None,
    cost_usd: Optional[float] = None,
    event_id: Optional[uuid.UUID] = None,
    bypass: bool = False,
    enforced: bool = True,
) -> uuid.UUID:
    """Persist one audit event. Returns the event's UUID (pre-generated by the
    caller — e.g. WalWriter — when event_id is given, so the WAL and the
    eventual Postgres row share the same id)."""
    event_id = event_id or uuid.uuid4()
    event = AuditEvent(
        id=event_id,
        session_id=session_id,
        agent_id=agent_id,
        agent_name=agent_name,
        tool_name=tool_name,
        tool_parameters=tool_parameters,
        tool_response=tool_response,
        policy_id=policy_id,
        policy_name=policy_name,
        decision=decision,
        decision_reason=decision_reason,
        sequence_number=sequence_number,
        duration_ms=duration_ms,
        risk_delta=risk_delta,
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        cost_usd=cost_usd,
        bypass=bypass,
        enforced=enforced,
    )
    session.add(event)
    await session.flush()
    logger.info("audit_event_written", tool_name=tool_name, decision=decision)

    if _export_dispatch_available and get_license_info().is_business:
        record = AuditEventRecord(
            id=event_id,
            session_id=session_id,
            agent_name=agent_name,
            tool_name=tool_name,
            tool_parameters=tool_parameters,
            decision=decision,
            decision_reason=decision_reason,
            policy_name=policy_name,
            duration_ms=duration_ms,
            created_at=datetime.now(timezone.utc),
        )
        asyncio.create_task(dispatch_audit_event(record))

    return event_id
