"""Writes immutable audit events for every intercepted tool call."""
import uuid
from typing import Any, Optional

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.logging import get_logger
from app.models.schemas import AuditEvent

logger = get_logger("audit_writer")


async def write_event(
    session: AsyncSession,
    session_id: uuid.UUID,
    agent_id: uuid.UUID,
    agent_name: str,
    tool_name: str,
    tool_parameters: dict[str, Any],
    decision: str,
    decision_reason: str,
    sequence_number: int,
    duration_ms: int,
    policy_id: Optional[uuid.UUID] = None,
    policy_name: Optional[str] = None,
    tool_response: Optional[dict] = None,
    risk_delta: int = 0,
    input_tokens: Optional[int] = None,
    output_tokens: Optional[int] = None,
    cost_usd: Optional[float] = None,
    event_id: Optional[uuid.UUID] = None,
    bypass: bool = False,
    enforced: bool = True,
) -> uuid.UUID:
    """Persist one audit event. Returns the event's UUID (pre-generated by the
    caller — e.g. WalWriter — when event_id is given, so the WAL and the
    eventual Postgres row share the same id)."""
    event_id = event_id or uuid.uuid4()
    event = AuditEvent(
        id=event_id,
        session_id=session_id,
        agent_id=agent_id,
        agent_name=agent_name,
        tool_name=tool_name,
        tool_parameters=tool_parameters,
        tool_response=tool_response,
        policy_id=policy_id,
        policy_name=policy_name,
        decision=decision,
        decision_reason=decision_reason,
        sequence_number=sequence_number,
        duration_ms=duration_ms,
        risk_delta=risk_delta,
        input_tokens=input_tokens,
        output_tokens=output_tokens,
        cost_usd=cost_usd,
        bypass=bypass,
        enforced=enforced,
    )
    session.add(event)
    await session.flush()
    logger.info("audit_event_written", tool_name=tool_name, decision=decision)
    return event_id
