#!/usr/bin/env bash
# AIControl Install Script
# Run from the repo root: bash install.sh
set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "${BOLD}=== AIControl Installer ===${NC}"
echo ""

# Check dependencies
for cmd in docker curl python3; do
  if ! command -v "$cmd" &>/dev/null; then
    echo -e "${RED}ERROR: $cmd is required but not installed.${NC}"
    exit 1
  fi
done
if ! docker compose version &>/dev/null; then
  echo -e "${RED}ERROR: docker compose v2 is required.${NC}"
  exit 1
fi

# Generate or load .env
if [ -f .env ]; then
  echo -e "${YELLOW}[skip]${NC} .env already exists — using existing configuration."
  echo "       Delete .env to reconfigure from scratch."
else
  echo -e "${BOLD}Let's configure AIControl.${NC}"
  echo ""

  read -rp "PostgreSQL password (default: auto-generated): " DB_PASS
  DB_PASS=${DB_PASS:-$(python3 -c "import secrets; print(secrets.token_urlsafe(24))")}

  read -rp "Secret key for JWT signing (default: auto-generated): " SECRET_KEY
  SECRET_KEY=${SECRET_KEY:-$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")}

  read -rp "Slack bot token (xoxb-..., or press Enter to skip): " SLACK_TOKEN
  SLACK_TOKEN=${SLACK_TOKEN:-xoxb-placeholder}

  read -rp "Slack signing secret (or press Enter to skip): " SLACK_SECRET
  SLACK_SECRET=${SLACK_SECRET:-placeholder}

  read -rp "Slack review channel (default: #aicontrol-reviews): " SLACK_CHANNEL
  SLACK_CHANNEL=${SLACK_CHANNEL:-#aicontrol-reviews}

  read -rp "Enterprise license key (press Enter for community edition): " LICENSE_KEY
  LICENSE_KEY=${LICENSE_KEY:-}

  cat > .env << ENVEOF
# PostgreSQL
POSTGRES_USER=aicontrol
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=aicontrol
POSTGRES_HOST=postgres
POSTGRES_PORT=5432

# SQLAlchemy
DATABASE_URL=postgresql+asyncpg://aicontrol:${DB_PASS}@postgres:5432/aicontrol

# OPA
OPA_URL=http://opa:8181

# App
APP_ENV=production
SECRET_KEY=${SECRET_KEY}

# Slack HITL
SLACK_BOT_TOKEN=${SLACK_TOKEN}
SLACK_SIGNING_SECRET=${SLACK_SECRET}
SLACK_REVIEW_CHANNEL=${SLACK_CHANNEL}

# React dashboard env vars (baked into frontend image at build time)
VITE_API_URL=http://localhost:8001

# CORS — comma-separated allowed origins for React dashboard. Change for remote deployments.
CORS_ORIGINS=http://localhost:3000

# Enterprise license (empty = Community plan, free)
# Set to your signed JWT license key to unlock Business or Enterprise features.
# Plan detection is runtime — no rebuild required after changing this.
AICONTROL_LICENSE_KEY=${LICENSE_KEY}

# Admin token (written below after first startup)
ADMIN_TOKEN=
ENVEOF

  echo ""
  echo -e "${GREEN}[done]${NC} .env created."
fi

# Pull images
echo ""
echo "[1/4] Pulling Docker images..."
docker compose -f docker-compose.yml -f docker-compose.app.yml pull --quiet --ignore-pull-failures || true
echo -e "${GREEN}[done]${NC} Images pulled (or using cached versions)."

# Start infra first
echo "[2/4] Starting infrastructure (postgres + opa)..."
docker compose -f docker-compose.yml up -d
echo -e "      Waiting for postgres..."
for i in $(seq 1 30); do
  if docker compose -f docker-compose.yml exec -T postgres \
     pg_isready -U aicontrol -d aicontrol &>/dev/null; then
    break
  fi
  sleep 2
  [ "$i" -eq 30 ] && { echo -e "${RED}ERROR: Postgres not ready.${NC}"; exit 1; }
done
echo -e "${GREEN}[done]${NC} Infrastructure ready."

# Run migrations
echo "[3/4] Running database migrations..."
docker compose -f docker-compose.yml -f docker-compose.app.yml \
  run --rm api alembic upgrade head
echo -e "${GREEN}[done]${NC} Migrations applied."

# Seed demo agents
echo "      Seeding demo agents..."
docker compose -f docker-compose.yml -f docker-compose.app.yml \
  run --rm -e PYTHONPATH=/app api python3 scripts/seed.py
echo -e "${GREEN}[done]${NC} Agents seeded."

# Start app services
docker compose -f docker-compose.yml -f docker-compose.app.yml up -d
echo -e "${GREEN}[done]${NC} All services started."

# Issue first admin token
echo ""
echo "[4/4] Issuing initial admin token..."
echo ""
ADMIN_OUTPUT=$(docker compose -f docker-compose.yml -f docker-compose.app.yml \
  exec api python3 -m scripts.issue_token \
  --role admin --desc "Initial admin token")
echo "$ADMIN_OUTPUT"
ADMIN_JWT=$(echo "$ADMIN_OUTPUT" | grep -oE 'eyJ[A-Za-z0-9._-]+')
# python3 (not `sed -i ''`, which is BSD/macOS-only syntax and fails on Linux's GNU sed)
python3 -c "
import re
with open('.env') as f:
    content = f.read()
content = re.sub(r'^ADMIN_TOKEN=.*$', 'ADMIN_TOKEN=${ADMIN_JWT}', content, flags=re.MULTILINE)
with open('.env', 'w') as f:
    f.write(content)
"
echo -e "${GREEN}[done]${NC} Admin token written to .env."

# Issue agent-scoped demo tokens
echo ""
echo "      Issuing demo agent tokens..."
{
  echo ""
  echo "# Demo tokens (auto-generated by install.sh)"
} >> .env

DEMO_LABELS=(LENDING HEALTHCARE ITSM MANUFACTURING SUPPORT REVOPS INSURANCE)
DEMO_UUIDS=(
  "00000000-0000-0000-0000-000000000010"
  "00000000-0000-0000-0000-000000000020"
  "00000000-0000-0000-0000-000000000030"
  "00000000-0000-0000-0000-000000000040"
  "00000000-0000-0000-0000-000000000050"
  "00000000-0000-0000-0000-000000000060"
  "00000000-0000-0000-0000-000000000070"
)
DEMO_NAMES=(
  "loan-underwriting-agent"
  "clinical-documentation-agent"
  "incident-response-agent"
  "supplier-sourcing-agent"
  "support-resolution-agent"
  "crm-automation-agent"
  "insurance-claims-agent"
)

for i in "${!DEMO_LABELS[@]}"; do
  DEMO_OUTPUT=$(docker compose -f docker-compose.yml -f docker-compose.app.yml \
    exec api python3 -m scripts.issue_token \
    --role agent --agent-id "${DEMO_UUIDS[$i]}" --desc "${DEMO_NAMES[$i]}")
  DEMO_JWT=$(echo "$DEMO_OUTPUT" | grep -oE 'eyJ[A-Za-z0-9._-]+')
  echo "DEMO_TOKEN_${DEMO_LABELS[$i]}=${DEMO_JWT}" >> .env
done
echo -e "${GREEN}[done]${NC} Demo tokens saved to .env."

echo ""
echo -e "${BOLD}${GREEN}=== Installation complete ===${NC}"
echo ""
echo "  API:       http://localhost:8001"
echo "  Dashboard: http://localhost:3000"
echo "  Health:    http://localhost:8001/health"
echo "  Debug:     http://localhost:8001/debug"
echo ""
echo -e "${YELLOW}Admin token and DEMO_TOKEN_* vars written to .env.${NC}"
echo ""
echo "Next: bash verify.sh"
echo ""
