"""Seed the 18 real-world library policies into the database.

Run: PYTHONPATH=/home/deven/aicontrol python scripts/seed_library_policies.py
Idempotent — safe to run multiple times.
"""
import asyncio
import json
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import text
from app.models.database import async_session_factory
from app.services.policy_loader import upsert_policies

# Library policy templates, v3 scope model.
#
# rule_type and action are gone. The tool binding moved out of the condition and
# into action_tool -- a single-tool denylist becomes the scope, a multi-tool one
# becomes tool_name_in (exact, not substring, matching base.rego). action became
# effect. parameter_match on the wildcard key "*" still means "any parameter
# value contains this"; /intercept flattens the parameters into
# all_params_text for it, because Cedar cannot iterate the context's own keys.
#
# Every entry below is verified to compile and to parse as Cedar.
LIBRARY_POLICIES = [
    {
        'name': 'block_shell_execution',
        'description': 'Block all shell execution tools — bash, exec, system calls',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'deny',
        'condition': {'tool_name_in': ['bash', 'exec_command', 'run_shell', 'execute_code', 'subprocess', 'system_call']},
        'active': False,
        'library': True,
        'priority': 10,
        'category': 'Dangerous Operations',
        'severity': 'critical',
        'compliance_frameworks': ['SOC2', 'ISO27001'],
    },
    {
        'name': 'block_file_deletion',
        'description': 'Block destructive file and database deletion operations',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'deny',
        'condition': {'tool_name_in': ['delete_file', 'remove_file', 'unlink', 'rmdir', 'drop_table', 'truncate_table']},
        'active': False,
        'library': True,
        'priority': 11,
        'category': 'Dangerous Operations',
        'severity': 'critical',
        'compliance_frameworks': ['SOC2'],
    },
    {
        'name': 'block_cloud_metadata_access',
        'description': 'Block access to cloud instance metadata service URLs (SSRF protection)',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'deny',
        'condition': {'parameter_match': {'url': {'contains_any': ['169.254.169.254', 'fd00:ec2::254']}}},
        'active': False,
        'library': True,
        'priority': 12,
        'category': 'Dangerous Operations',
        'severity': 'critical',
        'compliance_frameworks': ['SOC2', 'CIS'],
    },
    {
        'name': 'block_sensitive_file_reads',
        'description': 'Block reads of known sensitive system files',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'deny',
        'condition': {'parameter_match': {'path': {'contains_any': ['/etc/passwd', '/etc/shadow', '/.ssh/id_rsa', '/.aws/credentials']}}},
        'active': False,
        'library': True,
        'priority': 13,
        'category': 'Dangerous Operations',
        'severity': 'critical',
        'compliance_frameworks': ['SOC2', 'CIS'],
    },
    {
        'name': 'block_wildcard_queries',
        'description': 'Block wildcard (bulk) record queries — id set to wildcard',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'deny',
        'condition': {'parameter_match': {'id': {'equals': '*'}}},
        'active': False,
        'library': True,
        'priority': 20,
        'category': 'Data Protection',
        'severity': 'high',
        'compliance_frameworks': ['SOC2', 'GDPR'],
    },
    {
        'name': 'block_large_record_exports',
        'description': 'Block tool calls requesting more than 1,000 records',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'deny',
        'condition': {'numeric_conditions': {'limit': {'op': '>', 'value': 1000}}},
        'active': False,
        'library': True,
        'priority': 21,
        'category': 'Data Protection',
        'severity': 'high',
        'compliance_frameworks': ['SOC2', 'GDPR'],
    },
    {
        'name': 'block_prompt_injection_in_params',
        'description': 'Flag tool calls with prompt injection patterns in any parameter (OWASP LLM01)',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'review',
        'condition': {'parameter_match': {'*': {'contains_any': ['ignore previous instructions', 'disregard previous', 'bypass', 'jailbreak', 'dan mode']}}},
        'active': False,
        'library': True,
        'priority': 22,
        'category': 'Data Protection',
        'severity': 'high',
        'compliance_frameworks': ['OWASP-LLM'],
    },
    {
        'name': 'block_credential_patterns',
        'description': 'Flag tool calls containing credential or API key patterns in any parameter',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'review',
        'condition': {'parameter_match': {'*': {'contains_any': ['sk-', 'sk-ant-', 'api_key=', '-----BEGIN RSA', '-----BEGIN PRIVATE', 'ghp_', 'aws_secret_access']}}},
        'active': False,
        'library': True,
        'priority': 23,
        'category': 'Data Protection',
        'severity': 'high',
        'compliance_frameworks': ['SOC2', 'CIS'],
    },
    {
        'name': 'review_write_operations',
        'description': 'Send all write/create/update tool calls to human review',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'review',
        'condition': {'tool_name_contains': ['write', 'update', 'create', 'insert', 'patch', 'modify']},
        'active': False,
        'library': True,
        'priority': 30,
        'category': 'Human Review Gates',
        'severity': 'medium',
        'compliance_frameworks': [],
    },
    {
        'name': 'review_outbound_messaging',
        'description': 'Send all outbound communication tool calls to human review',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'review',
        'condition': {'tool_name_contains': ['send_email', 'post_message', 'send_sms', 'notify', 'alert']},
        'active': False,
        'library': True,
        'priority': 31,
        'category': 'Human Review Gates',
        'severity': 'medium',
        'compliance_frameworks': [],
    },
    {
        'name': 'review_high_value_transactions',
        'description': 'Send transactions over $10,000 to human review',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'review',
        'condition': {'numeric_conditions': {'amount': {'op': '>', 'value': 10000}}},
        'active': False,
        'library': True,
        'priority': 32,
        'category': 'Human Review Gates',
        'severity': 'medium',
        'compliance_frameworks': [],
    },
    {
        'name': 'rate_limit_external_api_calls',
        'description': 'Deny external HTTP/webhook calls after 20 per hour',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'deny',
        'condition': {'rate_limit': {'max_calls': 20, 'window': '60m', 'on_exceed': 'deny'}, 'tool_name_in': ['http_request', 'post_webhook']},
        'active': False,
        'library': True,
        'priority': 33,
        'category': 'Human Review Gates',
        'severity': 'medium',
        'compliance_frameworks': ['SOC2'],
    },
    {
        'name': 'block_bulk_account_lookup',
        'description': 'Block wildcard account or customer ID queries — finance compliance',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'deny',
        'condition': {'parameter_match': {'account_id': {'equals': '*'}, 'customer_id': {'equals': '*'}}},
        'active': False,
        'library': True,
        'priority': 40,
        'category': 'Industry: Finance',
        'severity': 'high',
        'compliance_frameworks': ['GLBA', 'SOC2'],
    },
    {
        'name': 'review_wire_transfers',
        'description': 'Send wire transfer and payment initiation tool calls to human review',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'review',
        'condition': {'tool_name_contains': ['wire_transfer', 'initiate_ach', 'send_payment']},
        'active': False,
        'library': True,
        'priority': 41,
        'category': 'Industry: Finance',
        'severity': 'high',
        'compliance_frameworks': ['GLBA', 'SOC2'],
    },
    {
        'name': 'deny_cross_patient_phi_access',
        'description': 'Block wildcard patient ID — PHI cross-patient data protection',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'deny',
        'condition': {'parameter_match': {'patient_id': {'equals': '*'}}},
        'active': False,
        'library': True,
        'priority': 50,
        'category': 'Industry: Healthcare',
        'severity': 'critical',
        'compliance_frameworks': ['HIPAA', 'SOC2'],
    },
    {
        'name': 'review_clinical_writes',
        'description': 'Send clinical write operations to human review — prescription and medication safety',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'review',
        'condition': {'tool_name_contains': ['create_prescription', 'update_medication', 'write_note']},
        'active': False,
        'library': True,
        'priority': 51,
        'category': 'Industry: Healthcare',
        'severity': 'high',
        'compliance_frameworks': ['HIPAA'],
    },
    {
        'name': 'block_iam_modifications',
        'description': 'Block IAM permission changes and MFA revocation',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'deny',
        'condition': {'tool_name_in': ['grant_admin', 'revoke_mfa', 'add_permission', 'disable_user']},
        'active': False,
        'library': True,
        'priority': 60,
        'category': 'Industry: Enterprise IT',
        'severity': 'critical',
        'compliance_frameworks': ['SOC2', 'ISO27001'],
    },
    {
        'name': 'review_infrastructure_changes',
        'description': 'Send infrastructure modification tool calls to human review',
        'principal_type': None,
        'principal_id': None,
        'action_tool': None,
        'resource_system': None,
        'effect': 'review',
        'condition': {'tool_name_contains': ['modify_firewall', 'update_dns', 'deploy_config', 'scale_service']},
        'active': False,
        'library': True,
        'priority': 61,
        'category': 'Industry: Enterprise IT',
        'severity': 'high',
        'compliance_frameworks': ['SOC2', 'ISO27001'],
    },
]


async def seed() -> None:
    """Upsert the library templates through the shared loader so each one is
    compiled to Cedar on the way in. A raw INSERT would leave cedar_text NULL and
    the template would silently match nothing when a customer activated it."""
    async with async_session_factory() as session:
        await upsert_policies(session, LIBRARY_POLICIES)
    print(f"Seeded {len(LIBRARY_POLICIES)} library policies.")


if __name__ == "__main__":
    asyncio.run(seed())
