"""add trial_expires_at to billing_customers

Revision ID: a3a97feb3f20
Revises: 67febff04874
Create Date: 2026-09-18 15:25:54.518632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3a97feb3f20'
down_revision: Union[str, Sequence[str], None] = '67febff04874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_customers', sa.Column('trial_expires_at', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_customers', 'trial_expires_at')
    # ### end Alembic commands ###
