"""
License key validation for AIControl.

The PUBLIC_KEY constant is the RSA public key generated by scripts/generate_keypair.py.
The matching private key is held securely by the AIControl team and used only by
scripts/issue_license.py to generate customer license JWTs.

This module has no FastAPI imports — it is a pure validation layer.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional

from jose import jwt, JWTError, ExpiredSignatureError


# ── Hardcoded public key ───────────────────────────────────────────────────────
# Replace this with the actual public key from scripts/generate_keypair.py output.
# This key is NOT secret — it validates signatures but cannot create them.
# Run: python scripts/generate_keypair.py
# Save the private key to your password manager; paste the public key here.
PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
PASTE_YOUR_GENERATED_PUBLIC_KEY_HERE
-----END PUBLIC KEY-----"""

ISSUER = "aictl.io"
ALGORITHM = "RS256"


class LicenseError(Exception):
    """Raised when a license key cannot be validated."""
    pass


@dataclass
class LicenseInfo:
    plan: str           # "community" | "business" | "enterprise"
    company: Optional[str]
    email: Optional[str]
    expires_at: Optional[datetime]

    @property
    def is_enterprise(self) -> bool:
        return self.plan == "enterprise"

    @property
    def is_business(self) -> bool:
        return self.plan in ("business", "enterprise")

    def to_dict(self) -> dict:
        return {
            "plan": self.plan,
            "company": self.company,
            "email": self.email,
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
            "is_enterprise": self.is_enterprise,
            "is_business": self.is_business,
        }


def decode_license_key(key: str) -> LicenseInfo:
    """
    Decode and validate an AIControl license JWT.

    Returns LicenseInfo(plan="community") for empty key.
    Raises LicenseError for any invalid, expired, or tampered key.
    """
    if not key or not key.strip():
        return LicenseInfo(
            plan="community",
            company=None,
            email=None,
            expires_at=None,
        )

    try:
        payload = jwt.decode(
            key,
            PUBLIC_KEY,
            algorithms=[ALGORITHM],
            issuer=ISSUER,
            options={"verify_exp": True},
        )
    except ExpiredSignatureError:
        raise LicenseError("License key has expired. Contact enterprise@aictl.io to renew.")
    except JWTError as e:
        error_msg = str(e).lower()
        if "issuer" in error_msg:
            raise LicenseError(f"License key has invalid issuer: {e}")
        raise LicenseError(f"License key is invalid: {e}")

    plan = payload.get("plan", "community")
    if plan not in ("community", "business", "enterprise"):
        raise LicenseError(f"License key contains unknown plan: {plan!r}")

    exp = payload.get("exp")
    expires_at = datetime.fromtimestamp(exp, tz=timezone.utc) if exp else None

    return LicenseInfo(
        plan=plan,
        company=payload.get("company"),
        email=payload.get("email"),
        expires_at=expires_at,
    )
